# Generated by Django 2.2 on 2021-11-22 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_names', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=2)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_change', models.DateField(auto_now=True)),
                ('date_history', models.TextField()),
                ('sintoms', models.TextField()),
                ('patient', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.TextField()),
                ('experience', models.TextField()),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.TextField()),
                ('latitude', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('adress', models.TextField()),
                ('contact', models.TextField()),
                ('userid', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.DateTimeField()),
                ('location', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('diagnosis', models.TextField()),
                ('recipe', models.TextField()),
                ('appoins', models.ForeignKey(on_delete=None, to='mainapp.Appoinment')),
                ('doctor_assigned', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
