# Generated by Django 2.2 on 2021-11-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211125_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='recipe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
