# Generated by Django 2.2 on 2021-11-25 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211125_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appoins',
            field=models.ForeignKey(on_delete='CASCADE', to='mainapp.Appoinment'),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='doctor_assigned',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
