# Generated by Django 2.2 on 2021-11-25 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211125_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appoins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Appoinment'),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='doctor_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
