# Generated by Django 2.2 on 2021-11-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211125_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='scheduled',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
