# Generated by Django 2.2 on 2021-11-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20211126_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
