# Generated by Django 2.2 on 2022-01-18 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_appoinment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_pago', models.DateField(blank=True, null=True)),
                ('precio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('couta_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Cuota')),
            ],
        ),
        migrations.RemoveField(
            model_name='appoint',
            name='appoins',
        ),
        migrations.RemoveField(
            model_name='appoint',
            name='doctor_assigned',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialist',
        ),
        migrations.DeleteModel(
            name='Appoinment',
        ),
        migrations.DeleteModel(
            name='Appoint',
        ),
    ]
