# Generated by Django 2.2 on 2022-06-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20220118_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('grado', models.CharField(max_length=100)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('data', models.TextField()),
            ],
        ),
    ]
