# Generated by Django 2.2 on 2022-06-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20220615_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='data',
            new_name='full_data',
        ),
    ]
