# Generated by Django 2.2 on 2022-06-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20220615_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='full_data',
            new_name='datos_inscripcion',
        ),
    ]
