# Generated by Django 2.2 on 2022-06-28 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20220616_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CENDI J.PIAGET', max_length=250)),
                ('weeks', models.IntegerField(default=20)),
                ('curr_week', models.IntegerField(default=1)),
                ('inicio_curso', models.DateField()),
                ('fin_curso', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='datos_inscripcion',
        ),
        migrations.AddField(
            model_name='alumno',
            name='date_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuota',
            name='grados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='historialpago',
            name='alumno',
            field=models.ForeignKey(on_delete=None, to='mainapp.Alumno'),
        ),
    ]
