# Generated by Django 2.2 on 2022-06-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20220628_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='curr_week',
        ),
        migrations.RemoveField(
            model_name='school',
            name='weeks',
        ),
    ]
