# Generated by Django 2.2 on 2022-06-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20220628_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cuota_week',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
