# Generated by Django 2.2 on 2022-06-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_school_cuota_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weeks',
        ),
        migrations.RenameField(
            model_name='cuota',
            old_name='date_pago',
            new_name='fin',
        ),
        migrations.RenameField(
            model_name='cuota',
            old_name='date_create',
            new_name='inicio',
        ),
        migrations.RenameField(
            model_name='cuota',
            old_name='grados',
            new_name='monto',
        ),
        migrations.RenameField(
            model_name='cuota',
            old_name='precio',
            new_name='recargo',
        ),
        migrations.RemoveField(
            model_name='historialpago',
            name='pagos',
        ),
        migrations.RemoveField(
            model_name='school',
            name='cuota_week',
        ),
    ]
