# Generated by Django 2.2 on 2022-06-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20220629_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='obligatorio',
            field=models.BooleanField(default=True),
        ),
    ]
