# Generated by Django 2.2 on 2022-06-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_cuota_obligatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
