# Generated by Django 2.2 on 2022-06-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_week_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='datos_inscripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
