# Generated by Django 2.2 on 2022-07-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alumno_datos_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='pronto_pago',
            field=models.FloatField(default=True, null=True),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete='cascade', to='mainapp.Alumno')),
                ('cuota', models.ForeignKey(on_delete='cascade', to='mainapp.Cuota')),
            ],
        ),
    ]
