# Generated by Django 2.2 on 2022-07-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20220701_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='date_create',
            field=models.DateField(blank=True, null=True),
        ),
    ]
