# Generated by Django 2.2 on 2022-07-04 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20220701_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_original',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='recargos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='total_pagado',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pago', models.DateField(auto_now_add=True)),
                ('pago', models.ManyToManyField(to='mainapp.Pago')),
            ],
        ),
    ]
