# Generated by Django 2.2 on 2022-07-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20220704_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pago',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Pago'),
        ),
    ]
