# Generated by Django 2.2 on 2022-07-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20220704_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_original',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pago',
            name='total_pagado',
            field=models.FloatField(default=0),
        ),
    ]
