# Generated by Django 2.2 on 2022-07-04 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20220704_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='alumno',
            field=models.ForeignKey(default=None, on_delete='cascade', to='mainapp.Alumno'),
            preserve_default=False,
        ),
    ]
