# Generated by Django 2.2 on 2022-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_ticket_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
