# Generated by Django 2.2 on 2022-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_week_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='week_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='mainapp.Week'),
        ),
    ]
