# Generated by Django 2.2 on 2022-07-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_pago_week_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sizes', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='mainapp.Cuota'),
        ),
        migrations.AddField(
            model_name='pago',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='mainapp.Producto'),
        ),
    ]
