# Generated by Django 2.2 on 2022-07-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20220706_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='producto',
            name='sizes',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
